latency-wait: 60
keep-going: True
printshellcmds: True

use-envmodules: True
use-singularity: True

# Cluster submission
jobname: "{rulename}.{jobid}"
drmaa: " -l centos=7 -V -cwd -j y -o ./log -e ./log -l h_rt={resources.hrs}:00:00 -l mfree={resources.mem}G -l cpuid_level=20 -pe serial {threads} -w n -S /bin/bash"
